# Generated by Django 3.1.7 on 2021-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210419_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='Users\\cihan\\OneDrive\\Masaüstü\\Yazılım\\myblog\\media', verbose_name='Makaleye Dosya Ekleyin'),
        ),
    ]
