# Generated by Django 3.1.7 on 2021-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(blank=True, max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yorum'),
        ),
    ]
